title: "💼 Projects"
items:
  - name: "Portfolio"
    description: "Sync from GitHub Personal Introduction & Website."
    bullet_points:
      - "Sync the GitHub Personal Introduction & Website and sync to every platform."
      - "One place to manage all my projects and skills."
    link: "https://github.com/HermanL02/Portfolio-site"
    deployment: "https://hermanyiqunliang.com"
    tag: "Next.js, CI/CD, GitHub Actions, Vercel, Tailwind CSS, Shadcn UI, TypeScript, JavaScript"
  - name: "Live Split Board"
    description: "LiveSplitBoard is a Next.js application that simplifies tracking apartment expenses among roommates and automatically sends updates to Discord when a new expense is created."
    bullet_points:
      - "Real-time expense tracking for shared living arrangements"
      - "Integration with Discord for seamless communication and updates"
      - "Built using TypeScript for type safety and improved code quality"
    link: "https://github.com/HermanL02/LiveSplitBoard"
    deployment: "https://live-split-board.vercel.app"
    tag: "Next.js, TypeScript, JavaScript, Discord API"
  - name: "GitHubStar"
    description: "GitHubStar is a JavaScript repository created in 2025 with a focus on showcasing best practices and innovative solutions."
    bullet_points:
      - "Utilizes modern JavaScript frameworks and libraries for efficient development"
      - "Includes comprehensive documentation for easy onboarding and maintenance"
      - "Actively maintained with regular updates and enhancements"
    link: "https://github.com/HermanL02/GitHubStar"
    tag: "JavaScript, Blockchain"
  - name: "ARWebsite"
    description: "ARWebsite is a Next.js-based project for Aurora Rangers website."
    bullet_points:
      - "Utilizes Next.js for a statically typed and more structured development experience"
      - "Incorporates AR technologies to enhance user interactions and experiences and create a seamless AR experience"
      - "Designed for creating visually engaging and interactive websites"
      - "Potential for integrating with AR hardware and devices for a seamless AR experience"
    link: "https://github.com/HermanL02/ARWebsite"
    deployment: "https://ar-website-silk-delta.vercel.app"
    tag: "Next.js, TypeScript, JavaScript"
  - name: "Koii-Task-Funder-Express"
    description: "Koii-Task-Funder-Express is a JavaScript repository created in 2024 for a task funding application."
    bullet_points:
      - "Utilizes Express framework for backend development"
      - "Implements JavaScript for server-side scripting"
      - "Focused on task funding functionality"
    link: "https://github.com/HermanL02/Koii-Task-Funder-Express"
    tag: "JavaScript"
  - name: "CSCI-4177-5709_Tutorial4"
    description: "This GitHub repository contains a tutorial for beginners in web development focusing on CSS. It covers various aspects of styling web pages using CSS."
    bullet_points:
      - "Step-by-step guide for CSS beginners"
      - "Hands-on practice exercises included"
      - "Demonstrates best practices for styling web pages"
    link: "https://github.com/HermanL02/CSCI-4177-5709_Tutorial4"
    tag: "CSS"
  - name: "CSCI-4177-5709_Tutorial5"
    description: "This GitHub repository contains a tutorial for CSCI-4177-5709 focusing on JavaScript development. It includes practical examples and exercises to help students learn key concepts in web development."
    bullet_points:
      - "Comprehensive tutorial for CSCI-4177-5709 students"
      - "Hands-on examples and exercises for JavaScript development"
      - "Focused on web development concepts"
    link: "https://github.com/HermanL02/CSCI-4177-5709_Tutorial5"
    tag: "JavaScript"
  - name: "CSCI-4177-5709_Tutorial2_Assignment1"
    description: "This GitHub repository contains a tutorial for Assignment 1 in the CSCI-4177-5709 course, focusing on TypeScript programming."
    bullet_points:
      - "Tutorial for Assignment 1 in CSCI-4177-5709 course"
      - "Focuses on TypeScript programming language"
      - "Helps students learn key concepts and practical applications of TypeScript"
    link: "https://github.com/HermanL02/CSCI-4177-5709_Tutorial2_Assignment1"
    tag: "TypeScript"
  - name: "CSCI-4177-5709_Tutorial7"
    description: "This repository contains code for a tutorial on JavaScript development, specifically focusing on CSCI-4177-5709 course material."
    bullet_points:
      - "Tutorial code for CSCI-4177-5709 course"
      - "JavaScript development examples"
      - "Hands-on practice exercises"
    link: "https://github.com/HermanL02/CSCI-4177-5709_Tutorial7"
    tag: "JavaScript"
  - name: "task-template"
    description: "The task-template repository is dedicated to enhancing access to decentralized technology through the use of JavaScript and support for popular NPM modules."
    bullet_points:
      - "Utilizes NodeJS 16 for task configuration"
      - "Written entirely in JavaScript for ease of use and flexibility"
      - "Supports a wide range of popular NPM modules for extended functionality"
    link: "https://github.com/koii-network/task-template"
    deployment: "https://koii.network"
    tag: "JavaScript"
  - name: "Koii Desktop Node"
    description: "The koii-node repository provides the essential infrastructure for executing Koii tasks, enabling decentralized computing on personal devices."
    bullet_points:
      - "Utilizes TypeScript for development"
      - "Promotes decentralization and widespread accessibility"
      - "Key role in the Koii network for efficient task execution"
    link: "https://github.com/koii-network/koii-node"
    deployment: "https://koii.network"
    tag: "TypeScript, decentralization, decentralized-computing, depin, koii, koii-network, web3"
  - name: "blog"
    description: "The 'blog' repository is a CSS-based project created in 2023 that serves as a template for designing and styling blog websites."
    bullet_points:
      - "Utilizes CSS for styling and design"
      - "Provides a foundation for creating blog layouts"
      - "Created in 2023"
    link: "https://github.com/koii-network/blog"
    tag: "CSS"
  - name: "Koii Docs"
    description: "The 'docs' repository is a JavaScript-based project created in 2023 with no specific topics listed. It serves as a documentation hub for various code snippets and examples."
    bullet_points:
      - "Contains comprehensive documentation for JavaScript code"
      - "Utilizes markdown for easy readability"
      - "Includes code examples and tutorials for beginners"
    link: "https://github.com/koii-network/docs"
    deployment: "https://www.koii.network/docs"
    tag: "JavaScript"
  - name: "create-task-cli"
    description: "The create-task-cli repository is a JavaScript command-line tool that allows users to easily create and manage tasks in a streamlined manner."
    bullet_points:
      - "Utilizes Node.js for backend functionality"
      - "Employs command-line interface for user-friendly interaction"
      - "Allows for seamless task creation and management"
    link: "https://github.com/koii-network/create-task-cli"
    tag: "JavaScript"
  - name: "orca-task-example"
    description: "orca-task-example is a TypeScript repository showcasing an example task implementation with no specific topics specified."
    bullet_points:
      - "Demonstrates TypeScript usage"
      - "Example task implementation"
      - "Created in 2025"
    link: "https://github.com/koii-network/orca-task-example"
    tag: "TypeScript"
  - name: "vps-node-setup"
    description: "The vps-node-setup repository is a collection of shell scripts designed to streamline the setup process for a Node.js environment on a virtual private server."
    bullet_points:
      - "Automates installation of Node.js and related dependencies"
      - "Optimizes server configuration for Node.js applications"
      - "Includes scripts for common server management tasks"
    link: "https://github.com/koii-network/vps-node-setup"
    tag: "Shell"
  - name: "ezsandbox"
    description: "EZsandbox is a comprehensive platform that serves as the ideal starting point for exploring the world of decentralization."
    bullet_points:
      - "Utilizes JavaScript for versatile development capabilities"
      - "Provides a user-friendly environment for beginners to dive into decentralized technologies"
      - "Offers a range of tools and resources to support learning and experimentation"
    link: "https://github.com/koii-network/ezsandbox"
    tag: "JavaScript"
  - name: "builder-247"
    description: "Builder-247 is a Python project created in 2025 with a focus on streamlining the process of building applications."
    bullet_points:
      - "Utilizes Python for development"
      - "Designed to simplify the construction of applications"
      - "Created in 2025"
    link: "https://github.com/koii-network/builder-247"
    tag: "Python"
  - name: "orca-task-template"
    description: "The orca-task-template repository contains a JavaScript project template for creating and managing tasks in a streamlined manner."
    bullet_points:
      - "Uses JavaScript for scripting tasks"
      - "Provides a structured template for task management"
      - "Designed for easy customization and extension"
    link: "https://github.com/koii-network/orca-task-template"
    tag: "JavaScript"
  - name: "task-X"
    description: "task-X is a JavaScript repository created in 2023 with no specific topic. It showcases various JavaScript functionalities and techniques."
    bullet_points:
      - "Utilizes JavaScript for coding"
      - "Demonstrates modern JavaScript practices"
      - "Potential resource for learning JavaScript"
    link: "https://github.com/koii-network/task-X"
    tag: "JavaScript"
  - name: "StarAndFollowSupportRepo"
    description: "StarAndFollowSupportRepo is a repository designed to provide support and guidance for users on how to star and follow projects on GitHub."
    bullet_points:
      - "Step-by-step instructions on how to star and follow repositories"
      - "Interactive tutorials for new GitHub users"
      - "Community forum for asking questions and sharing tips"
    link: "https://github.com/koii-network/StarAndFollowSupportRepo"
    tag: ""
  - name: "task-tracker"
    description: "The task-tracker repository is a JavaScript-based project created in 2023 for managing and tracking tasks efficiently."
    bullet_points:
      - "Built with JavaScript for dynamic functionality"
      - "Allows users to create, update, and delete tasks"
      - "Utilizes modern web development techniques for a seamless user experience"
    link: "https://github.com/koii-network/task-tracker"
    tag: "JavaScript"
  - name: "task-middle-server-template"
    description: "This repository is a template for a middle server that acts as an intermediary between client and backend server, written in JavaScript."
    bullet_points:
      - "Utilizes Node.js for server-side scripting"
      - "Implements Express.js for handling routing and middleware"
      - "Includes examples of how to integrate with databases like MongoDB"
      - "Designed to streamline development of middle server functionality"
    link: "https://github.com/koii-network/task-middle-server-template"
    tag: "JavaScript"
  - name: "task-examples"
    description: "This repository contains a collection of JavaScript code examples for various tasks and functionalities."
    bullet_points:
      - "Includes examples for common JavaScript tasks such as array manipulation, string operations, and DOM manipulation."
      - "Utilizes modern JavaScript features such as arrow functions, template literals, and async/await."
      - "Provides clear and concise examples to help developers understand and implement common tasks in JavaScript."
    link: "https://github.com/koii-network/task-examples"
    tag: "JavaScript"
  - name: "namespace-wrapper"
    description: "The Namespace Wrapper is a crucial utility package designed to simplify task node operations and interface with the Koii Network infrastructure using a unified API."
    bullet_points:
      - "Written in TypeScript for type safety and modern development practices"
      - "Provides abstraction for complex task node operations, streamlining development processes"
      - "Acts as a bridge between Koii tasks and the network infrastructure for seamless integration"
    link: "https://github.com/koii-network/namespace-wrapper"
    tag: "TypeScript"
  - name: "kpl-token-migration-script"
    description: "This repository contains a JavaScript script for migrating tokens in the KPL platform."
    bullet_points:
      - "Automates token migration process"
      - "Uses JavaScript for scripting"
      - "Designed for KPL platform"
    link: "https://github.com/koii-network/kpl-token-migration-script"
    tag: "JavaScript"
  - name: "kpl-helper"
    description: "The kpl-helper repository is a JavaScript tool designed to streamline and simplify the process of working with Amazon Kinesis Producer Library (KPL)."
    bullet_points:
      - "Automates configuration setup for KPL"
      - "Provides utility functions for common KPL tasks"
      - "Offers a user-friendly interface for managing KPL operations"
    link: "https://github.com/koii-network/kpl-helper"
    tag: "JavaScript"
  - name: "Koii-AI-Coach"
    description: "Koii-AI-Coach is a JavaScript-based repository that serves as an AI-powered coaching tool for personal development and growth."
    bullet_points:
      - "Utilizes machine learning algorithms for personalized coaching recommendations"
      - "Integrates with user data to tailor coaching sessions"
      - "Employs interactive features for engaging user experience"
    link: "https://github.com/koii-network/Koii-AI-Coach"
    tag: "JavaScript"
  - name: "k2-web3.js"
    description: "The k2-web3.js repository is a TypeScript-based JavaScript SDK that enables developers to interact with accounts and programs on the Koii network using the K2 JSON RPC API."
    bullet_points:
      - "Provides a seamless way to connect and communicate with the Koii network"
      - "Supports the latest features and functionalities of the K2 JavaScript SDK (v1.x)"
      - "Written in TypeScript for improved type safety and code maintainability"
    link: "https://github.com/koii-network/k2-web3.js"
    tag: "TypeScript"
  - name: "k2-metadata-cli"
    description: "k2-metadata-cli is a command-line tool for managing and manipulating metadata within files."
    bullet_points:
      - "Supports extraction and modification of metadata in various file formats"
      - "Provides a simple and intuitive interface for interacting with metadata"
      - "Allows for batch processing of metadata across multiple files"
    link: "https://github.com/koii-network/k2-metadata-cli"
    tag: "JavaScript"

