title: "💼 Projects"
items:
  - name: "Portfolio"
    description: "Sync from GitHub Personal Introduction & Website."
    bullet_points:
      - "Sync the GitHub Personal Introduction & Website and sync to every platform."
      - "One place to manage all my projects and skills."
    link: "https://github.com/HermanL02/Portfolio-site"
    deployment: "https://hermanyiqunliang.com"
    tag: "Next.js, React, Node.js, CI/CD, GitHub Actions, Vercel, Tailwind CSS, Shadcn UI, TypeScript, JavaScript"
  - name: "Koii Desktop Node"
    description: "The koii-node repository provides the essential infrastructure for executing Koii tasks, enabling decentralized computing on personal devices."
    bullet_points:
      - "Utilizes TypeScript for development"
      - "Promotes decentralization and widespread accessibility"
      - "Key role in the Koii network for efficient task execution"
    link: "https://github.com/koii-network/koii-node"
    deployment: "https://koii.network"
    tag: "TypeScript, Decentralization, Electron, IPC, Node.js, React"
  - name: "Namespace Wrapper"
    description: "The Namespace Wrapper is a crucial utility package designed to simplify task node operations and interface with the Koii Network infrastructure using a unified API."
    bullet_points:
      - "Written in TypeScript for type safety and modern development practices"
      - "Provides abstraction for complex task node operations, streamlining development processes"
      - "Acts as a bridge between Koii tasks and the network infrastructure for seamless integration"
    link: "https://github.com/koii-network/namespace-wrapper"
    tag: "TypeScript"
  - name: "Live Split Board"
    description: "LiveSplitBoard is a Next.js application that simplifies tracking apartment expenses among roommates and automatically sends updates to Discord when a new expense is created."
    bullet_points:
      - "Real-time expense tracking for shared living arrangements"
      - "Integration with Discord for seamless communication and updates"
      - "Built using TypeScript for type safety and improved code quality"
    link: "https://github.com/HermanL02/LiveSplitBoard"
    deployment: "https://live-split-board.vercel.app"
    tag: "Next.js, React, Node.js, Vercel, Tailwind CSS, TypeScript, JavaScript, Discord API"
  - name: "ARWebsite"
    description: "ARWebsite is a Next.js-based project for Aurora Rangers website."
    bullet_points:
      - "Utilizes Next.js for a statically typed and more structured development experience"
      - "Incorporates AR technologies to enhance user interactions and experiences and create a seamless AR experience"
      - "Designed for creating visually engaging and interactive websites"
      - "Potential for integrating with AR hardware and devices for a seamless AR experience"
    link: "https://github.com/HermanL02/ARWebsite"
    deployment: "https://ar-website-silk-delta.vercel.app"
    tag: "Next.js, React, Node.js, Vercel, Tailwind CSS, TypeScript, JavaScript"
  - name: "Koii Task Funder Express"
    description: "Koii Task Funder Express is a JavaScript repository created in 2024 for a task funding application."
    bullet_points:
      - "Utilizes Express framework for backend development"
      - "Implements JavaScript for server-side scripting"
      - "Focused on task funding functionality"
    link: "https://github.com/HermanL02/Koii-Task-Funder-Express"
    tag: "JavaScript, Solana, Decentralization, Express"
  - name: "Task Template"
    description: "The Task Template is dedicated to enhancing access to decentralized technology through the use of JavaScript and support for popular NPM modules."
    bullet_points:
      - "Written entirely in JavaScript for ease of use and flexibility"
      - "Supports on-chain task execution"
    link: "https://github.com/koii-network/task-template"
    tag: "JavaScript, Solana"
  - name: "Koii Blog"
    description: "Koii Blog serves as a template for designing and styling blog websites."
    bullet_points:
      - "Utilizes CSS for styling and design"
    link: "https://github.com/koii-network/blog"
    tag: "Ruby, CSS, Markdown"
  - name: "Koii Docs"
    description: "The Koii Docs serves as a documentation hub for various code snippets and examples."
    bullet_points:
      - "Contains comprehensive documentation for Koii"
      - "Utilizes markdown for easy readability"
      - "Includes code examples and tutorials for beginners"
    link: "https://github.com/koii-network/docs"
    deployment: "https://www.koii.network/docs"
    tag: "JavaScript, Markdown, Docusaurus"
  - name: "Create Task CLI"
    description: "The Create Task CLI allows users to manage the on-chain and off-chain tasks seamlessly."
    bullet_points:
      - "Utilizes Node.js for backend functionality"
      - "Allows for seamless task creation and management"
    link: "https://github.com/koii-network/create-task-cli"
    tag: "TypeScript, Node.js, CLI"
  - name: "Orca Task Example"
    description: "Orca Task Example is a TypeScript repository showcasing an example task implementation with no specific topics specified."
    bullet_points:
      - "Demonstrates TypeScript usage"
      - "Example task implementation"
    link: "https://github.com/koii-network/orca-task-example"
    tag: "TypeScript, Decentralization"
  - name: "VPS Node Setup"
    description: "The VPS Node Setup is a collection of shell scripts designed to streamline the setup process for a Node.js environment on a virtual private server."
    bullet_points:
      - "Automates installation of Node.js and related dependencies"
      - "Optimizes server configuration for Node.js applications"
      - "Includes scripts for common server management tasks"
    link: "https://github.com/koii-network/vps-node-setup"
    tag: "Shell"
  - name: "EZsandbox"
    description: "EZsandbox is a comprehensive platform that serves as the ideal starting point for exploring the world of decentralization."
    bullet_points:
      - "Utilizes JavaScript for versatile development capabilities"
      - "Provides a user-friendly environment for beginners to dive into decentralized technologies"
      - "Offers a range of tools and resources to support learning and experimentation"
    link: "https://github.com/koii-network/ezsandbox"
    tag: "JavaScript, Decentralization, Markdown"
  - name: "Builder-247"
    description: "Builder-247 is a Python project created in 2025 with a focus on streamlining the process of building applications."
    bullet_points:
      - "Utilizes Python for development"
      - "Designed to simplify the construction of applications"
      - "AI-powered application builder"
      - "Now, deprecated, because of Claude Code"
    link: "https://github.com/koii-network/builder-247"
    tag: "Python, AI, Decentralization, RAG, LLM"
  - name: "Orca Task Template"
    description: "The Orca Task Template contains a JavaScript project template for creating and managing tasks in a streamlined manner."
    bullet_points:
      - "Uses JavaScript for scripting tasks"
      - "Deploy containerized task to decentralized devices"
    link: "https://github.com/koii-network/orca-task-template"
    tag: "JavaScript, Decentralization, Docker, Podman, Python"
  - name: "Task-X"
    description: "Koii Decentralized Task"
    bullet_points:
      - "Decentralized task for end-users to scrape data from the web and report it to the centralized server."
      - "It scrapes twitter data and reports it to the centralized server."
    link: "https://github.com/koii-network/task-X"
    tag: "JavaScript, Decentralization, Web Scraping"
  - name: "Star and Follow Support Repo"
    description: "Koii Decentralized Task"
    bullet_points:
      - "Decentralized task for end-users to star and follow repositories on GitHub."
    link: "https://github.com/koii-network/StarAndFollowSupportRepo"
    tag: "JavaScript, TypeScript, Blockchain, Decentralization"
  - name: "Task Tracker"
    description: "The Task Tracker is to track the Koii Tasks and provide it to the data team for analysis."
    bullet_points:
      - "It tracks the Koii Tasks and provides it to the data team for analysis."
    link: "https://github.com/koii-network/task-tracker"
    tag: "JavaScript"
  - name: "Task Middle Server Template"
    description: "The Task Middle Server Template is a template for a middle server that acts as an intermediary between decentralized tasks and backend server. "
    bullet_points:
      - "Utilizes Node.js for server-side scripting"
      - "Implements Express.js for handling routing and middleware"
      - "Includes examples of how to integrate with databases like MongoDB"
      - "Designed to streamline development of middle server functionality"
    link: "https://github.com/koii-network/task-middle-server-template"
    tag: "JavaScript"
  - name: "Task Examples"
    description: "The Task Examples is a collection of JavaScript code examples for various tasks and functionalities for Koii."
    bullet_points:
      - "It is a collection of JavaScript code examples for various tasks and functionalities."
    link: "https://github.com/koii-network/task-examples"
    tag: "JavaScript"

  - name: "kpl-token-migration-script"
    description: "This repository contains a JavaScript script for migrating tokens in the KPL platform."
    bullet_points:
      - "Automates token migration process"
      - "Uses JavaScript for scripting"
      - "Designed for KPL platform"
    link: "https://github.com/koii-network/kpl-token-migration-script"
    tag: "JavaScript"
  - name: "KPL Helper"
    description: "The KPL Helper designed to streamline and simplify the process of working with Koii Tokens."
    bullet_points:
      - "Automates configuration setup for Koii Tokens"
      - "Provides utility functions for common Koii Tokens tasks"
      - "Offers a user-friendly interface for managing Koii Tokens operations"
    link: "https://github.com/koii-network/kpl-helper"
    tag: "JavaScript"
  - name: "Koii AI Coach"
    description: "Decentralized AI Task"
    bullet_points:
      - "Use Ollama to deploy AI models to the Koii Network"
      - "End Users can offer their own AI chat or API service to the Koii Network and earn rewards"
    link: "https://github.com/koii-network/Koii-AI-Coach"
    tag: "JavaScript"
  - name: "K2 Web3.js"
    description: "The K2 Web3.js is a TypeScript-based JavaScript SDK that enables developers to interact with accounts and programs on the Koii network using the K2 JSON RPC API."
    bullet_points:
      - "Fork of Solana Web3.js"
      - "Provides a seamless way to connect and communicate with the Koii network"
      - "Supports the latest features and functionalities of the K2 JavaScript SDK"
    link: "https://github.com/koii-network/k2-web3.js"
    tag: "TypeScript, JavaScript, Decentralization"
  - name: "K2 Metadata CLI"
    description: "The K2 Metadata CLI is a command-line tool for managing and manipulating metadata within files."
    bullet_points:
      - "Supports extraction and modification of metadata in various file formats"
      - "Provides a simple and intuitive interface for interacting with metadata"
      - "Allows for batch processing of metadata across multiple files" 
      - "It is a command-line tool for managing and manipulating metadata within files."
    link: "https://github.com/koii-network/k2-metadata-cli"
    tag: "JavaScript"
  - name: "CSCI-4177-5709 Tutorial 4"
    description: "This GitHub repository contains a tutorial for beginners in web development focusing on CSS. It covers various aspects of styling web pages using CSS."
    bullet_points:
      - "Step-by-step guide for CSS beginners"
      - "Hands-on practice exercises included"
      - "Demonstrates best practices for styling web pages"
    link: "https://github.com/HermanL02/CSCI-4177-5709_Tutorial4"
    tag: "Angular, CSS"
  - name: "CSCI-4177-5709 Tutorial 5"
    description: "This GitHub repository contains a tutorial for CSCI-4177-5709 focusing on JavaScript development. It includes practical examples and exercises to help students learn key concepts in web development."
    bullet_points:
      - "Comprehensive tutorial for CSCI-4177-5709 students"
      - "Hands-on examples and exercises for JavaScript development"
      - "Focused on web development concepts"
    link: "https://github.com/HermanL02/CSCI-4177-5709_Tutorial5"
    tag: "Angular, CSS"
  - name: "CSCI-4177-5709 Tutorial 2 Assignment 1"
    description: "This GitHub repository contains a tutorial for Assignment 1 in the CSCI-4177-5709 course, focusing on TypeScript programming."
    bullet_points:
      - "Tutorial for Assignment 1 in CSCI-4177-5709 course"
      - "Focuses on TypeScript programming language"
      - "Helps students learn key concepts and practical applications of TypeScript"
    link: "https://github.com/HermanL02/CSCI-4177-5709_Tutorial2_Assignment1"
    tag: "Angular, CSS"
  - name: "CSCI-4177-5709 Tutorial 7"
    description: "This repository contains code for a tutorial on JavaScript development, specifically focusing on CSCI-4177-5709 course material."
    bullet_points:
      - "Tutorial code for CSCI-4177-5709 course"
      - "JavaScript development examples"
      - "Hands-on practice exercises"
    link: "https://github.com/HermanL02/CSCI-4177-5709_Tutorial7"
    tag: "Angular, CSS"